#serviceAccount:
#  iamrole: arn:aws:iam::548286011133:role/eksctl-xeneta-rates-nodegroup-xen-NodeInstanceRole-RI20LC9VDFCA

#deployIngress:
#  clusterName: xeneta-rates

nameSpace:
  name: rates

secrets:
  name: rates-db-secret
  dbpwd: VGd1eWFzZGluYWRtbjYzNjI=

nodeService:
  name: rates-service
  port: 3000

dbService:
  name: rates-db-service
#  rdsEndPoint: xeneta-rates.cwatgephvnv6.us-east-1.rds.amazonaws.com

deployment:
  name: rates-deployment
  #containers:
#    image: 041096/ratesoperations:1.0.0
  dbUser: postgres
  dbName: rates
  replicas: 3

ingress:
  name: xeneta-rates-service
  albName: xeneta-rates-alb
  albScheme: internet-facing
  #albSubnets: subnet-05e8d06af36be45a9, subnet-090d0693eb471b8d1
  #albSg: sg-0fe7cdc3f46c564d8
  listenerPort: '[{"HTTP": 80}]'
  targetType: instance
  protocol: HTTP
  hcPort: traffic-port
  hcProtocol: HTTP
  hcPath: /
  hcinterval: '30'
  hctimeout: '10'
  hchthreshold: '3'
  hcuhthreshold: '3'
  successCode: '200'