apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nodeService.name }}
  labels:
    app: rates
  namespace: {{ .Values.nameSpace.name }}
spec:
  type: NodePort
  selector:
    app: rates
  ports:
    - port: {{ .Values.nodeService.port }}
      targetPort: 3000
