apiVersion: v1
kind: Secret
metadata: 
  name: {{ .Values.secrets.name }}
  labels:
    app: rates
  namespace: {{ .Values.nameSpace.name }}
type: opaque
data:
  rates_db_password: {{ .Values.secrets.dbpwd }}