apiVersion: v1
kind: Service
metadata: 
  name: {{ .Values.dbService.name }}
  labels:
    app: rates
  namespace: {{ .Values.nameSpace.name }}
spec:
  type: ExternalName # External Name Service in k8s
  externalName: {{ .Values.dbService.rdsEndPoint }} # AWS RDS Postgres End Point